/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#102000",
        "secondary-fixed-dim": "#91db2a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#f5fff7",
        "tertiary-fixed": "#cce5ff",
        "secondary": "#416900",
        "surface-container-highest": "#dae2fd",
        "tertiary": "#006194",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f3ff",
        "on-primary-fixed": "#002114",
        "surface-variant": "#dae2fd",
        "on-error-container": "#93000a",
        "inverse-primary": "#68dba9",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "outline-variant": "#bccac0",
        "inverse-on-surface": "#eef0ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#3d4a42",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "on-secondary-container": "#457000",
        "surface": "#faf8ff",
        "background": "#faf8ff",
        "primary-fixed-dim": "#68dba9",
        "on-tertiary-fixed": "#001d31",
        "primary-container": "#00855d",
        "inverse-surface": "#283044",
        "tertiary-container": "#007bb9",
        "on-surface": "#131b2e",
        "primary-fixed": "#85f8c4",
        "on-tertiary-fixed-variant": "#004b73",
        "on-primary-fixed-variant": "#005137",
        "secondary-container": "#acf847",
        "tertiary-fixed-dim": "#93ccff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        "surface-tint": "#006c4a",
        "primary": "#006948",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#acf847",
        "outline": "#6d7a72",
        "on-secondary-fixed-variant": "#304f00",
        "surface-container": "#eaedff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-sm": "0.75rem",
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "margin-lg": "2rem",
        "margin": "1.25rem",
        "margin-sm": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "gutter": "1rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "numeric-hero-mobile": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "numeric-hero": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "numeric-hero-mobile": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "numeric-hero": ["36px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-sm": ["17px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "700" }]
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        }
      },
      animation: {
        slideUp: 'slideUp 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
      }
    }
  },
  plugins: [],
}
